### PR TITLE
Language style support for various new languages

### PR DESCRIPTION
**Pull request by theryan722**
Languages Added: Ada, Assembly, Batch, Fortran, HTML/XML/YAML, Lisp, Lua, Perl, PHP, Ruby and SmallTalk.

### CODE REVIEW

**Comment by theryan722** [comment]
Could you please merge this?

**Comment by jacobslusser** [comment]
The merge took some time because there were a few convention inconsistencies. I want to keep all the casing conventions with [Microsoft recommendations](https://msdn.microsoft.com/en-us/library/vstudio/ms229043(v=vs.100).aspx). I also removed instances of faux lexers and style constants. As you know there is no actual C# lexer, only the C++ lexer. My fear is that if we suggest there is a dedicated C# lexer it will eventually lead to confusion with the users. In addition I double-checked all the documentation and filled in some gaps where I could.

It was a lot to go through and so it's quite possible I made some mistakes. If you find something or want to discuss it further, let me know.

Thanks again for the contribution.

**Comment by theryan722** [comment]
No problem. I added them because at the time I felt it would be easier to just select it for your language instead of determining which one would be compatible with your language, but its for the best. Thank you for correcting my evil-doings.

On another note, I have become really interested in this project, I hope to be contributing more soon.

**Comment by jacobslusser** [comment]
I welcome the help! :)

If you want to coordinate anything just shoot me an email: jslusser [dot] mobile [at] gmail [dot] com.

**Pull request merged**
