### PR TITLE
Fixed bug in CreateLoader, added encoding param.

### PR DESCRIPTION
**Pull request by HTD**
There was no possibility of reading files with various encodings, I've added additional parameter to CreateLoader method which allows to do so. Tested, works.

### CODE REVIEW

**Comment by jacobslusser** [comment]
Your understanding of the encoding argument used in the `ILoader` ctor is incorrect. This value specifies what encoding to use when *writing* data to ScintillaNET, not *reading* data from a file. 

When loading a file the general sequence you would follow is:
1). Read bytes/stream from disk (your application)
2). Convert bytes to characters using desired encoding (your application)
3). Add characters to Scintilla via `AddData` (your application)
4). Convert characters to Scintilla's internal encoding (ScintillaNET)

Your assumption is that the encoding used here is related to step 2, however, it is actually related to step 4. This encoding argument is used when converting characters to Scintilla's internal byte format--which should be of no concern for you (and is always UTF-8, BTW).

If that doesn't make sense, let me know and I'll try and explain it differently. But the short answer is that if you want to use a different encoding when loading a file, there is nothing we need to change in ScintillaNET to make that work. That is all a function of your application.

**Comment by HTD** [comment]
I used the example recipe found on wiki to implement background loading. I opened a file with Windows CP1250 encoding and all national characters were mangled. Then I added encoding parameter to CreateLoader and the file opened correctly. What did I do wrong? In ScintillaNET source code I found internal Scintilla encoding should not be changed. Of course I can convert encoding of the file in app code - but it entirely defeats the point of background loading.

Here's my code used to load the document:

        public async Task<Document> LoadFileAsync(ILoader loader, string path, Encoding encoding, bool detectBOM, CancellationToken cancellationToken) {
            const int bufferSize = 1024 * 1024;
            try {
                using (var file = new FileStream(path, FileMode.Open, FileAccess.ReadWrite, FileShare.ReadWrite, bufferSize: bufferSize, useAsync: true))
                using (var reader = new StreamReader(file, encoding, detectBOM)) {
                    var count = 0;
                    var buffer = new char[bufferSize];
                    while ((count = await reader.ReadAsync(buffer, 0, buffer.Length).ConfigureAwait(false)) > 0) {
                        cancellationToken.ThrowIfCancellationRequested();
                        if (!loader.AddData(buffer, count)) throw new IOException("The data could not be added to the loader.");
                    }
                    return loader.ConvertToDocument();
                }
            } catch {
                loader.Release();
                throw;
            }
        }

        public async void LoadFile(string path, Encoding encoding = null, bool detectBOM = false) {
            var _enabled = Enabled;
            var _readonly = ReadOnly;
            Enabled = false;
            ReadOnly = true;
            try {
                if (encoding == null) encoding = Encoding.UTF8;
                var loader = CreateLoader(1024 * 1024, encoding);
                if (loader == null) throw new ApplicationException("Unable to create loader.");
                var cts = new CancellationTokenSource();
                var document = await LoadFileAsync(loader, path, encoding, detectBOM, cts.Token);
                Document = document;
                ReleaseDocument(document);
                ApplyContainerLexer();
            } catch (OperationCanceledException) { }
            catch (Exception x) {
                MessageBox.Show(this, x.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            } finally {
                Enabled = _enabled;
                ReadOnly = _readonly;
            }
        }

If `CreateLoader()` was called without `encoding` param (original ScintillaNET) I got corrupt text from CP1250 no matter which encoding I chose for `StreamReader`.
My fix doesn't break anything but allows files with ANSI encodings to display correctly - if the encoding parameter is set correctly.

Try for yourself, here's the sample: "Zażółć gęślą jaźń." - use Notepad++ to save this sample as Windows-1250 encoding. Then try to open it using `CreateLoader()`.

**Comment by jacobslusser** [comment]
No worries about the encoding stuff. :)

Regarding the text being corrupt when you first create the control... I'm unable to reproduce the issue. When I use the snippet from the Wiki article on a new control I don't have any problems with the text.

Can you provide a code sample that demonstrates the issue you're seeing?

**Comment by HTD** [comment]
https://github.com/HTD/ScintillaNET/tree/master/Test

Here's the sample. It has to be cloned as whole project because of encoded test files.

1. After starting program - select any menu option - this would load one of the test files.
2. The correct text is "Zażółć gęślą jaźń.". But you will get something else - corrupt text.
3. Select any menu option again - you should see correct text. With any encoding option.
4. Uncomment line 20 in Test.cs ("scintilla1.Document = Document.Empty;")
5. Run program and select any option
6. Now text should be displayed correctly for each test from the first time.

**Comment by jacobslusser** [comment]
I can confirm the issue using your test. I'm not sure yet what the cause is but I'll continue to investigate.

**Comment by jacobslusser** [comment]
I created Issue #87 to track the resolution of this.

**Pull request closed without merging**
