### PR TITLE
Added Indention property to the Lines class.

### PR DESCRIPTION
**Pull request by JohnyMac**
It have been fully tested.

### CODE REVIEW

**Comment by jacobslusser** [comment]
Thanks for the code! I didn't even know about that property, but it sure will make auto indentation much easier.

**Comment by theryan722** [comment]
You have it written as "Indention", wouldn't it be better if it was "Indentation"?

**Comment by jacobslusser** [comment]
Yes. LOL. I completely missed that.

**Comment by jacobslusser** [comment]
Commit a2e105d8c375c8f55fc231d5dd59d87d37618c09.

**Comment by theryan722** [comment]
I kept typing
```c#
Scintilla1.Lines(curline).Indentation == #here;
```
Which kept giving me errors and I kept getting angrier and angrier until
finally I checked the IntelliSense and realized.

On Thu, Jul 2, 2015 at 3:54 PM, jacobslusser <notifications@github.com>
wrote:

> Yes. LOL. I completely missed that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jacobslusser/ScintillaNET/pull/48#issuecomment-118148417>
> .
>



-- 
Ryan O'Day
------------------------------------
Business Email: bionetworkscorp@gmail.com
Business Website: www.bionetworkscorp.net

**Comment by theryan722** [comment]
I kept typing:

```c#
Scintilla1.Lines(curline).Indentation == numberhere;
```

Which kept giving me errors and I kept getting angrier and angrier until
finally I checked the IntelliSense and realized.

**Comment by JohnyMac** [comment]
Sorry for that, I am not English :P
LOL.

**Pull request merged**
